[build]
  command = "yarn build"
  publish = "build/"
  edge_functions = "functions"

[[edge_functions]]
  path = "/(famille|ville)/*"
  function = "ssr-page"

[[edge_functions]]
  path = "/sitemap.xml"
  function = "sitemap"

[[redirects]]
  from = "https://armorial.bertranddaure.fr/*"
  to = "https://armorialdefrance.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
