[build]
  command = "yarn build"
  publish = "build/"
  edge_functions = "functions"

[[edge_functions]]
  path = "/(famille|ville)/*"
  function = "ssr-page"

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
