[build]
  command = "yarn build"
  publish = "build/"
  functions = "functions/basic"
  edge_functions = "functions/edge"

[[edge_functions]]
  path = "/(famille|ville)/*"
  function = "ssr-page"

[[edge_functions]]
  path = "/sitemap.xml"
  function = "sitemap"

[[redirects]]
  from = "https://armorial.bertranddaure.fr/*"
  to = "https://armorialdefrance.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/scripts/partners/umami.js"
  to = "https://cloud.umami.is/script.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
